name: Lint

on:
  push:
    branches:
      - master

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --config=flake8 .
